export const IMAGES = {
  vineoLogo: '/assets/images/vineo-logo.png',
  homeBg: '/assets/images/homebg.png',
  graph: '/assets/images/graph.svg',
  coin: '/assets/images/logo/coin.svg',
  vector: '/assets/images/logo/vector.svg',
  settings: '/assets/images/logo/settings.svg',
  star: '/assets/images/logo/star.svg',
  inbox: '/assets/images/logo/inbox-Regular.svg',
  home: '/assets/images/logo/home.svg',
  google: '/assets/images/logo/flat-color-icons_google.png',
  vineo_ilustracian: '/assets/images/homepage/VINEO_ILUSTRACIàN.png',
  answer2: '/assets/images/homepage/answer2.png',
  bottle2: '/assets/images/homepage/bottle2.png',
  graphGif: '/assets/images/homepage/graphGIf1.png',
  hand: '/assets/images/homepage/hand.png',
  graphDetail: '/assets/images/homepage/graphDetail.png',
  bottleImage: '/assets/images/homepage/bottleImage1.png',
  fifthBg: '/assets/images/homepage/fifthBg.png',
  whatsapp: '/assets/icons/icons8-whatsapp-480.png',
  footer: '/assets/images/homepage/letter-1-removebg-preview1.png',
  whatsappf: '/assets/images/footer/whatsapp.png',
  ig: '/assets/images/footer/ig.png',
  fb: '/assets/images/footer/fb.png',
  Capa_1: '/assets/images/recommendation/Capa_1.png',
  gif: '/assets/gifs/home/vineo.gif',
  winegif: '/assets/gifs/home/bottle.gif',
};
